port: 8080
matrix:
  homeserver_url: "https://matrix.example.com/"
  access_token: verysecrettoken
  mx_id: "@bot:example.com"
  rooms:
    "!roomidhere": "token, generate one using pwgen or a similar tool"
