name: create release dist
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: [gpg, native-x86_64-linux]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: actions/setup-home@972508aa672ab101fd85eaffab9671c0a641bc7a # v1
        with:
          gpg-privkey: ${{ secrets.GPG_PRIVKEY }}
          gpg-key-id: ${{ vars.GPG_KEY_ID }}
      - name: build
        run: nix build .#static
      - name: create archive
        run: |
          mkdir -p dist/release
          cp -L --no-preserve --all result/bin/cpanel-matrix dist/release/${FORGEJO_REPOSITORY##*/}-${FORGEJO_REF_NAME}
      - name: create release
        id: release
        uses: bart/forgejo-release@74bd5d3064257c896a1499ddcf18ac1161189d47 # v2
        with:
          direction: upload
          gpg-private-key: ${{ secrets.GPG_PRIVKEY }}
  build-deb:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [bookworm, trixie, sid]
    container:
      image: debian:${{ matrix.distro }}-slim
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          path: "${{ github.event.repository.name }}-${{ github.ref_name }}"
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential debhelper dh-golang golang-go git curl
      - name: Build Debian package
        run: |
          pushd "$SOURCE_PACKAGE_DIR"

          VERSION=${FORGEJO_REF_NAME#v}
          echo "Appending version $VERSION to Debian changelo for ${{ matrix.distro }}"

          cat << EOF > debian/changelog.new
          cpanel-matrix (${VERSION}-1) ${{ matrix.distro }}; urgency=low

            * Automated release build for Debian ${{ matrix.distro }}.

           -- ${{ github.actor }} <git@bartoostveen.nl>  $(date -R)

          EOF
          cat debian/changelog >> debian/changelog.new
          mv debian/changelog.new debian/changelog
          dpkg-buildpackage -us -uc

          popd
        env:
          SOURCE_PACKAGE_DIR: "${{ github.event.repository.name }}-${{ github.ref_name }}"
      - name: Test Debian package
        run: |
          DEB_FILE=$(ls *.deb | head -n 1)
          apt-get install -y ./$DEB_FILE
          cpanel-matrix --help || true
          ls -la /etc/cpanel-matrix/config.yaml
          ls -la /lib/systemd/system/cpanel-matrix.service
      - name: Upload Debian package to Forgejo registry
        run: |
          DEB_FILE=$(ls *.deb | head -n 1)
          curl --user "${FORGEJO_REPOSITORY%/*}:${FORGEJO_TOKEN}" \
            --upload-file "${DEB_FILE}" \
            "${FORGEJO_API_URL}/packages/${FORGEJO_REPOSITORY%/*}/debian/pool/${{ matrix.distro }}/main/upload"
